repos:
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: '2.1.5'
  hooks:
  - id: fasterer
    stages: [commit]
  - id: reek
    stages: [commit]
  - id: rubocop
    args: ['-A']
    stages: [commit]
- repo: local
  hooks:
    - id: rspec
      name: Run rspec tests
      stages: [commit]
      entry: /bin/bash -c 'bundle exec rspec'
      language: script
      verbose: true
      always_run: true
